name: hello-world
on:
  push:
  pull_request:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        if: github.event_name == 'push'
        run: echo "Push Event"
      - name: my-other-step
        if: github.event_name == 'pull_request'
        run: echo "Pull Request Event"
